config/routes.rb
Rails.application.routes.draw do

  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  #ユーザー用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  #ゲストユーザー用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :admin do
    root to: "users#index"
    resources :users, only: [:show, :edit, :update]
    resources :post_study_methods, only: [:show,:index, :destroy] do
      resources :comments, only: [:destroy]
    end
    get "/search", to: "post_study_methods#search"
  end

  scope module: :public do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update]
    resources :subjects, except: [:index, :show]
    resources :tasks, except: [:index, :show] do
      resources :achieved_tasks, only: [:create]
    end
    resources :rewards, except: [:index, :show] do
      resources :exchanged_rewards, only: [:create, :destroy]
    end
    resources :post_study_methods, except: [:new] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get "/achieved_tasks", to: "achieved_tasks#index"
    get "/favorites", to: "favorites#index"
    get "/search", to: "post_study_methods#search"
    get "/quit", to: "users#quit"
    patch "/out", to: "users#out"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/achieved_task.rb
class AchievedTask < ApplicationRecord
  belongs_to :user
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post_study_method

  validates :comment, presence: true

end

app/models/exchanged_reward.rb
class ExchangedReward < ApplicationRecord
  belongs_to :user
  belongs_to :reward

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_study_method

end

app/models/post_study_method.rb
class PostStudyMethod < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  #あるユーザーにいいねされているかを判別するメソッド
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  #投稿を検索するメソッド
  def self.search_for(word)
    PostStudyMethod.where("title LIKE ? or body LIKE ?", "%#{word}%", "%#{word}%")
  end

end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :user
  has_many :exchanged_rewards

  validates :content, presence: true

end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :user
  has_many :tasks

  validates :name, presence: true

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :subject

  validates :content, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :subjects, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :post_study_methods, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :achieved_tasks, dependent: :destroy
  has_many :rewards, dependent: :destroy
  has_many :exchanged_rewards, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :school_year, presence: true

  #jhs→中学生、hs→高校生
  enum school_year: {jhs_1:0, jhs_2:1, jhs_3:2, hs_1:3, hs_2:4, hs_3:5, adult:6}

  #ゲストユーザーログイン
  def self.guest
    find_or_create_by!(name: "ゲストユーザー" , email: "guest@example.com", school_year: 6) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.email = "guest@example.com"
    end
  end

  #プロフィール画像表示
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to request.referer
  end

end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/post_study_methods_controller.rb
class Admin::PostStudyMethodsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @post_study_methods = PostStudyMethod.all
  end

  def show
    @post_study_method = PostStudyMethod.find(params[:id])
  end

  def search
    @word = params[:word]
    @post_study_methods = PostStudyMethod.search_for(@word)
    render :index
  end

  def destroy
    post_study_method = PostStudyMethod.find(params[:id])
    post_study_method.destroy
    redirect_to admin_post_study_methods_path
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :school_year, :email, :is_deleted)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/post_study_methods_helper.rb
module Admin::PostStudyMethodsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/post_study_methods/index.html.erb
<div class="container">
  <div class="row mt-4">
    <h3 class="text-info col-8 offset-1">投稿一覧</h3>
    <div class="col-3">
      <%= form_with url: admin_search_path, method: :get do |f| %>
        <div class="input-group">
          <%= f.text_field :word, placeholder: "キーワードを入力", class: "form-control input-group-prepend" %>
          <span class="input-group-btn input-group-append">
            <%= f.submit "検索", class: "btn btn-primary" %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-11 offset-1">
      <% @post_study_methods.reverse_each do |post_study_method| %>
        <div class="border-bottom">
          <%= link_to admin_user_path(post_study_method.user) do %>
            <span><%= post_study_method.user.name %></span>
          <% end %>
          <span><%= post_study_method.created_at.strftime('%Y/%m/%d %H:%M') %></span>
          <h5>
            <%= link_to admin_post_study_method_path(post_study_method) do %>
              <%= post_study_method.title %>
            <% end %>
          </h5>
          <p><%= post_study_method.body %></p>
          <span>いいね数: <%= post_study_method.favorites.count %></span>
          <span class="ml-3">コメント数: <%= link_to "#{post_study_method.comments.count}", admin_post_study_method_path(post_study_method) %></span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/post_study_methods/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <div class="mt-4">
        <h4 class="text-info">投稿詳細</h4>
      </div>
      <div class="card mt-4">
        <div class="card-header">
          <span>
            <%= link_to admin_user_path(@post_study_method.user) do %>
              <%= @post_study_method.user.name %>
            <% end %>
          </span>
          <span class="ml-5">
            <%= @post_study_method.created_at.strftime('%Y/%m/%d %H:%M')%>
          </span>
        </div>
        <div class="card-body">
          <h5 class="card-title">
            <%= @post_study_method.title %>
          </h5>
          <p class="card-text">
            <%= @post_study_method.body %>
          </p>
        </div>
        <div class="card-footer">
          <span>いいね数: <%= @post_study_method.favorites.count %></span>
          <span class="ml-4">コメント数: <%= @post_study_method.comments.count %></span>
          <div class="mt-2">
            <%= link_to "この投稿を削除する", admin_post_study_method_path(@post_study_method), method: :delete, data: {confirm: "本当に削除しますか？"} %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-7 offset-1">
      <div class="mt-4">
        <h4 class="text-info">コメント一覧(<%= @post_study_method.comments.count %>件)</h4>
      </div>
      <div class="mt-4">
        <% @post_study_method.comments.reverse_each do |comment| %>
          <div class="border-bottom">
            <%= link_to admin_user_path(comment.user) do %>
              <span><%= comment.user.name %></span>
            <% end %>
            <span><%= comment.created_at.strftime("%Y/%m/%d %H:%M") %></span>
            <p><%= comment.comment %></p>
            <p><%= link_to "このコメントを削除する", admin_post_study_method_comment_path(comment.post_study_method, comment), method: :delete, data: {confirm: "本当に削除しますか？"} %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>