config/routes.rb
Rails.application.routes.draw do

  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  #ユーザー用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  #ゲストユーザー用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :admin do
    root to: "users#index"
    resources :users, only: [:show, :edit, :update]
    resources :post_study_methods, only: [:show,:index, :destroy] do
      resources :comments, only: [:destroy]
    end
    get "/search", to: "post_study_methods#search"
  end

  scope module: :public do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update]
    resources :subjects, except: [:index, :show]
    resources :tasks, except: [:index, :show] do
      resources :achieved_tasks, only: [:create]
    end
    resources :rewards, except: [:index, :show] do
      resources :exchanged_rewards, only: [:create, :destroy]
    end
    resources :post_study_methods, except: [:new] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get "/achieved_tasks", to: "achieved_tasks#index"
    get "/favorites", to: "favorites#index"
    get "/search", to: "post_study_methods#search"
    get "/quit", to: "users#quit"
    patch "/out", to: "users#out"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/achieved_task.rb
class AchievedTask < ApplicationRecord
  belongs_to :user
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post_study_method

  validates :comment, presence: true

end

app/models/exchanged_reward.rb
class ExchangedReward < ApplicationRecord
  belongs_to :user
  belongs_to :reward

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_study_method

end

app/models/post_study_method.rb
class PostStudyMethod < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  #あるユーザーにいいねされているかを判別するメソッド
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  #投稿を検索するメソッド
  def self.search_for(word)
    PostStudyMethod.where("title LIKE ? or body LIKE ?", "%#{word}%", "%#{word}%")
  end

end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :user
  has_many :exchanged_rewards

  validates :content, presence: true

end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :user
  has_many :tasks

  validates :name, presence: true

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :subject

  validates :content, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :subjects, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :post_study_methods, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :achieved_tasks, dependent: :destroy
  has_many :rewards, dependent: :destroy
  has_many :exchanged_rewards, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :school_year, presence: true

  #jhs→中学生、hs→高校生
  enum school_year: {jhs_1:0, jhs_2:1, jhs_3:2, hs_1:3, hs_2:4, hs_3:5, adult:6}

  #ゲストユーザーログイン
  def self.guest
    find_or_create_by!(name: "ゲストユーザー" , email: "guest@example.com", school_year: 6) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.email = "guest@example.com"
    end
  end

  #プロフィール画像表示
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to request.referer
  end

end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :school_year, :email, :is_deleted)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/post_study_methods_helper.rb
module Admin::PostStudyMethodsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/users/edit.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-12 offset-4">
      <h3 class="text-info">ユーザー情報編集</h3>
      <div class="mt-4">
        <%= form_with model: @user, url: admin_user_path(@user.id), method: :patch do |f| %>
          <div class="field mb-4">
            <%= f.label :name, "ユーザーネーム" %><br>
            <%= f.text_field :name %>
          </div>
          <div class="field mb-4">
            <%= f.label :school_year, "学年" %><br>
            <%= f.select :school_year, [["中学1年","jhs_1"], ["中学2年","jhs_2"], ["中学3年","jhs_3"], ["高校1年","hs_1"], ["高校2年","hs_2"], ["高校3年","hs_3"], ["大学生以上","adult"]]%>
          </div>
          <div class="field mb-4">
            <%= f.label :email, "メールアドレス" %><br>
            <%= f.email_field :email %>
          </div>
          <div class="field mb-5">
            <%= f.label "ステータス" %><br>
            <%= f.radio_button :is_deleted, false %>
            <%= f.label :is_deleted, "有効" %>
            <%= f.radio_button :is_deleted, true %>
            <%= f.label :is_deleted, "退会" %>
          </div>
          <div class="field">
            <%= f.submit "変更を保存", class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col-10 offset-1">
      <h3 class="text-info">ユーザー一覧</h3>
      <div class="mt-5">
        <table class="table table-bordered table-hover">
          <thead class="bg-light">
            <tr>
              <th>ユーザーID</th>
              <th>ユーザーネーム</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= link_to admin_user_path(user) do %>
                    <%= user.id %>
                  <% end %>
                </td>
                <td>
                  <%= link_to admin_user_path(user) do %>
                    <%= user.name %>
                  <% end %>
                </td>
                <td><%= user.email %></td>
                <td>
                  <% if user.is_deleted == false %>
                    <p>有効</p>
                  <% else %>
                    <p>退会</p>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-6 offset-3">
      <h3 class="text-info">ユーザー情報詳細</h3>
      <div class="mt-4">
        <table class="table table-bordered">
          <tr>
            <th>ユーザーID</th>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <th>ユーザーネーム</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <th>学年</th>
            <td><%= @user.school_year_i18n %></td>
          </tr>
          <tr>
            <th>ステータス</th>
            <td>
              <% if @user.is_deleted == false %>
                <p>有効</p>
              <% else %>
                <p>退会</p>
              <% end %>
            </td>
          </tr>
        </table>
      </div>
      <div>
        <%= link_to "編集する", edit_admin_user_path(@user), class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>