config/routes.rb
Rails.application.routes.draw do

  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  #ユーザー用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  #ゲストユーザー用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :admin do
    root to: "users#index"
    resources :users, only: [:show, :edit, :update]
    resources :post_study_methods, only: [:show,:index, :destroy] do
      resources :comments, only: [:destroy]
    end
    get "/search", to: "post_study_methods#search"
  end

  scope module: :public do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update]
    resources :subjects, except: [:index, :show]
    resources :tasks, except: [:index, :show] do
      resources :achieved_tasks, only: [:create]
    end
    resources :rewards, except: [:index, :show] do
      resources :exchanged_rewards, only: [:create, :destroy]
    end
    resources :post_study_methods, except: [:new] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get "/achieved_tasks", to: "achieved_tasks#index"
    get "/favorites", to: "favorites#index"
    get "/search", to: "post_study_methods#search"
    get "/quit", to: "users#quit"
    patch "/out", to: "users#out"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/achieved_task.rb
class AchievedTask < ApplicationRecord
  belongs_to :user
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post_study_method

  validates :comment, presence: true

end

app/models/exchanged_reward.rb
class ExchangedReward < ApplicationRecord
  belongs_to :user
  belongs_to :reward

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_study_method

end

app/models/post_study_method.rb
class PostStudyMethod < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  #あるユーザーにいいねされているかを判別するメソッド
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  #投稿を検索するメソッド
  def self.search_for(word)
    PostStudyMethod.where("title LIKE ? or body LIKE ?", "%#{word}%", "%#{word}%")
  end

end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :user
  has_many :exchanged_rewards

  validates :content, presence: true

end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :user
  has_many :tasks

  validates :name, presence: true

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :subject

  validates :content, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :subjects, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :post_study_methods, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :achieved_tasks, dependent: :destroy
  has_many :rewards, dependent: :destroy
  has_many :exchanged_rewards, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :school_year, presence: true

  #jhs→中学生、hs→高校生
  enum school_year: {jhs_1:0, jhs_2:1, jhs_3:2, hs_1:3, hs_2:4, hs_3:5, adult:6}

  #ゲストユーザーログイン
  def self.guest
    find_or_create_by!(name: "ゲストユーザー" , email: "guest@example.com", school_year: 6) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.email = "guest@example.com"
    end
  end

  #プロフィール画像表示
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to request.referer
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :school_year, :email, :is_deleted)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header.html.erb
<header class="shadow-sm bg-info">
  <nav class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand p-4 text-white" href="/admin">e-study</a>
      <!--ハンバーガーメニュー-->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "ユーザー一覧", admin_root_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "投稿一覧", admin_post_study_methods_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link text-white" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_user_header.html.erb
<header class="shadow">
  <nav class="bg-info navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand p-4 text-white" href="/">e-study</a>
      <!--ハンバーガーメニュー-->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "タスク管理", new_task_path, class: "nav-link text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "ランキング", users_path, class: "nav-link text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", post_study_methods_path, class: "nav-link text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "マイページ", user_path(current_user), class: "nav-link text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link text-white" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "nav-link text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: "nav-link text-white" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <% if user_signed_in? %>
    <div class="d-flex align-items-center justify-content-end">
      <%= link_to user_path(current_user) do %>
        <p class="my-2 ml-5"><%= image_tag current_user.get_profile_image(50,50) %></p>
      <% end %>
      <p class="my-2 ml-2"><%= current_user.name %></p>
      <p class="my-2 ml-2"><%= current_user.school_year_i18n %></p>
      <p class="my-2 ml-3 mr-auto">トータル勉強時間: <%= current_user.achieved_tasks.sum(:study_hour) %>時間</p>
      <p class="my-2 mr-2">P: <%= current_user.point %>ポイント</p>
      <p class="my-2">→</p>
      <p class="my-2 ml-2 mr-5"><%= link_to "ポイントを交換する", new_reward_path, class: "btn btn-outline-info" %></p>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EStudy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <% if admin_signed_in? %>
      <%= render "layouts/admin_header" %>
    <% else %>
      <%= render "layouts/user_header" %>
    <% end %>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <main>
      <%= yield %>
    </main>
    <footer class="bg-info text-white pt-4 pb-3 mt-auto">
      <div class="container">
        <div class="row">
          <p class="col-12 text-center">© 2022 Naoki Matsumoto</p>
        </div>
      </div>
    </footer>
  </body>
</html>